image: node:8-alpine

before_script:
  - apk add --no-cache bash curl git

cache:
  paths:
    - /node_modules/
    - /public/
    - /dist/

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: build
  script:
    - npm i
  only:
    changes:
      - spec/**/*

test:
  stage: test
  script:
    - npm run test
  only:
    changes:
      - spec/**/*

build:
  stage: build
  script:
    - npm run build
  only:
    changes:
      - spec/**/*

pages:
  stage: deploy
  before_script:
    - apk add --no-cache bash curl git
  script:
    - rm -r public
    - cp -r /dist/* public/*
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
    changes:
      - swagger.yaml
  cache:
    paths: []
  only:
    refs:
      - master
    changes:
      - spec/**/*

trigger_libs:
  stage: deploy
  before_script:
    - apk add --no-cache bash curl git
  script:
    - "curl -X POST -F token=${TRIGGER_RAVIMO_API_GLOBAL_LIB_ANGULAR} -F ref=master https://gitlab.com/api/v4/projects/13483643/trigger/pipeline"
  cache:
    paths: []
  only:
    refs:
      - master
    changes:
      - spec/**/*
