image: maven:3.6.1-jdk-13-alpine

before_script:
    - apk add --no-cache bash curl git

only:
  refs:
    - master
  changes:
    - swagger.yaml
  
stages:
  - deploy

pages:
  stage: deploy
  before_script:
    - apk add --no-cache bash curl git
  script:
    - ./scripts/generate_html_documentation.sh
    - cp swagger.yaml public/swagger.yaml
  artifacts:
    paths:
    - public

trigger_libs:
  stage: deploy
  before_script:
    - apk add --no-cache bash curl git
  script:
    - "curl -X POST -F token=${TRIGGER_RAVIMO_API_GLOBAL_LIB_ANGULAR} -F ref=master https://gitlab.com/api/v4/projects/13483643/trigger/pipeline"
