image: node:8-alpine

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm i
  cache:
    paths:
      - node_modules/
  only:
    changes:
      - spec/**/*

test:
  stage: test
  script:
    - npm run test
  cache:
    paths:
      - node_modules/
  only:
    changes:
      - spec/**/*

build:
  stage: build
  script:
    - npm run build
  cache:
    paths:
      - dist/
  only:
    changes:
      - spec/**/*

pages:
  stage: deploy
  before_script:
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
        export TARGET_FOLDER=public;
      else
        export TARGET_FOLDER=public/${CI_COMMIT_REF_NAME};
      fi
    - echo "Saving html into ${TARGET_FOLDER} directory..."
  script:
    - rm -rf "${TARGET_FOLDER}"
    - mkdir -p "${TARGET_FOLDER}"
    - cp -r /dist/* "${TARGET_FOLDER}/*"
  artifacts:
    paths:
    - public
  cache: {}
  only:
    refs:
      - master
    changes:
      - spec/**/*

trigger_libs:
  stage: deploy
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${TRIGGER_RAVIMO_API_GLOBAL_LIB_ANGULAR} -F ref=master https://gitlab.com/api/v4/projects/13483643/trigger/pipeline"
  cache: {}
  only:
    refs:
      - master
    changes:
      - spec/**/*
