image: node:8-alpine

variables:
  ORIGINAL_REPOSITORY: "ravimosharksas/apis/global/documentation"

stages:
  - install
  - test
  - build
  - deploy
  - notify

install:
  stage: install
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/
  only:
    changes:
      - spec/**/*
      - .gitlab-ci.yml
      - package.json

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - node_modules/
  only:
    changes:
      - spec/**/*
      - .gitlab-ci.yml
      - package.json

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
    expire_in: 15 days
  only:
    changes:
      - spec/**/*
      - .gitlab-ci.yml
      - package.json

pages:
  stage: deploy
  before_script:
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
        export TARGET_FOLDER=public;
      else
        export TARGET_FOLDER=public/${CI_COMMIT_REF_NAME};
      fi
    - echo "Saving html into ${TARGET_FOLDER} directory..."
  script:
    - rm -rf "${TARGET_FOLDER}"
    - mkdir -p "${TARGET_FOLDER}"
    - cp -r dist/* "${TARGET_FOLDER}"
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - spec/**/*
      - .gitlab-ci.yml
      - package.json

trigger_libs:
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${TRIGGER_RAVIMO_API_GLOBAL_LIB_ANGULAR} -F ref=master https://gitlab.com/api/v4/projects/13483643/trigger/pipeline"
  only:
    refs:
      - master
    changes:
      - spec/**/*
      - .gitlab-ci.yml
      - package.json
    variables:
      - $CI_PROJECT_PATH == "${ORIGINAL_REPOSITORY}"
