image: maven:3.6.1-jdk-13-alpine

before_script:
    - apk add --no-cache bash curl git

stages:
  - build
  - deploy

pages:
  stage: build
  before_script:
    - apk add --no-cache bash curl git
  script:
    - ./scripts/generate_html_documentation.sh
    - cp swagger.yaml public/swagger.yaml
  artifacts:
    paths:
    - public
  only:
  - master

#TODO: trigger to each library
# trigger_build:
#   stage: deploy
#   script:
#     - "curl -X POST -F token=${TRIGGER_TOKEN_LIB_ANDROID} -F ref=master https://gitlab.com/api/v4/projects/12239915/trigger/pipeline"